---
# Install EPEL and upgrade all existing packages, or installing user specified packages may fail
- name: Upgrade packages to latest
  package: name=* state=latest

- name: Install EPEL repo
  package: name=epel-release state=latest

- name: Install default packages
  package: name="{{ item }}" state=present update_cache=yes
  with_items: "{{ common_default_packages }}"
  register: default_packages

- name: Update mlocate db
  command: updatedb
  when: "'mlocate' in common_default_packages and default_packages.changed"
