---
# Create swap immediately with 'register' commands vs 'notify', so later plays
# don't fail due to insufficent memory
- name: Verify swapfile status
  stat: path={{ common_swapfile_location }}
  register: swap_status

- name: Create swapfile
  command: dd if=/dev/zero of={{ common_swapfile_location }} bs=1M count={{ common_swapfile_size }}
  become: yes
  when: swap_status.stat.exists == False

- name: Set swapfile permissions
  file:
    path: "{{ common_swapfile_location }}"
    owner: root
    group: root
    mode: 0600
  become: yes
  when: swap_status.stat.exists == False or (swap_status.stat.exists == true and swap_status.stat.mode != 0600)

- name: Format swapfile
  command: mkswap {{ common_swapfile_location }}
  become: yes
  when: swap_status.stat.exists == False

- name: Enable swapfile
  command: swapon {{ common_swapfile_location }}
  become: yes
  when: swap_status.stat.exists == False

- name: Persist swapfile to fstab
  mount: name=none src={{ common_swapfile_location }} fstype=swap opts=defaults passno=0 dump=0 state=present
  become: yes
  when: swap_status.stat.exists == False
