---

- name: restart auditd
  service: name=auditd state=restarted enabled=yes

- name: reload sshd
  service: name=sshd state=reloaded enabled=yes

- name: restart yum-cron
  service: name=yum-cron state=restarted enabled=yes
